---
- name: Set up Kubernetes VMs
  hosts: vms
  tasks:
    - name: Install ssh-ed25519 public key for root user
      authorized_key:
        user: root
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICJHwlIktJUwqHSF23fM+X0112WDmESV90XkKQse//tt dmz.oneill@gmail.com-2024-automation"
        state: present
