---
- name: Deploy Prometheus and Grafana on Kubernetes
  hosts: local
  tasks:
    - name: Create namespace for monitoring
      command: kubectl apply -f templates/monitoring-namespace.yaml.j2

    - name: Deploy Node Exporter DaemonSet
      command: kubectl apply -f templates/prometheus.yaml.j2

    - name: Deploy Grafana 
      command: kubectl apply -f templates/grafana.yaml.j2
