---
- name: Render Apps definition template
  hosts: master
  gather_facts: false
  tasks:

    - name: Remove apps
      command: kubectl delete -f /tmp/apps.yaml
      ignore_errors: true

    - name: Create apps
      template:
        src: templates/apps.yaml.j2
        dest: /tmp/apps.yaml

    - name: Apply apps
      command: kubectl apply -f /tmp/apps.yaml
      ignore_errors: true