---
- name: Get local IP address
  gather_facts: yes
  vars_files:
    - facts/infra.yaml
  hosts: localhost
  tasks:
    - name: Get local IP address
      shell: "{{ LOCAL_IP_CMD }}"
      register: local_ip

- name: Render PV definition template
  hosts: master
  gather_facts: yes
  vars_files:
    - facts/infra.yaml
  tasks:
    - name: Set fact
      set_fact:
        nfs_server_ip: "{{ hostvars['localhost']['local_ip']['stdout'] }}"
      
    - name: Render PV definition template
      template:
        src: templates/nfs-pv.yaml.j2
        dest: nfs-pv.yaml
      vars:
        nfs_server_ip: "{{ nfs_server_ip }}"

    - name: Apply PV
      command: kubectl apply -f nfs-pv.yaml
      ignore_errors: true