---
- name: Setup Harbor container registry on Fedora with containerd
  hosts: master
  become: true
  tasks:
    - name: Install necessary packages for Containerd
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - containerd.io
        - python3-pip

    - name: Install Docker Compose via pip (optional, if needed)
      pip:
        name: docker-compose

    - name: Start and enable Containerd service
      systemd:
        name: containerd
        state: started
        enabled: yes

    - name: Download Harbor installer
      get_url:
        url: https://github.com/goharbor/harbor/releases/download/v2.11.0/harbor-online-installer-v2.11.0.tgz
        dest: /tmp/harbor-online-installer.tgz

    - name: Extract Harbor installer
      unarchive:
        src: /tmp/harbor-online-installer.tgz
        dest: /opt
        remote_src: yes

    - name: Copy Harbor configuration template
      template:
        src: harbor.yml.j2  # Replace with your actual Harbor configuration template
        dest: /opt/harbor/harbor.yml

    - name: Install Harbor with Containerd
      shell: |
        cd /opt/harbor
        ./install.sh --with-containerd

    - name: Ensure Harbor is running
      systemd:
        name: harbor
        state: started
        enabled: yes

- name: Configure Kubernetes to use the Harbor registry
  hosts: vms
  become: true
  tasks:
    - name: Create a Kubernetes secret for the Harbor registry
      shell: |
        kubectl create secret docker-registry harbor-regcred \
          --docker-server={{ hostvars['registry'].ansible_default_ipv4.address }} \
          --docker-username=admin \
          --docker-password=Harbor12345 \
          --docker-email=admin@example.com
      args:
        creates: /etc/kubernetes/harbor-registry-secret-created

    - name: Patch the default service account to use the registry secret
      shell: |
        kubectl patch serviceaccount default \
          -p '{"imagePullSecrets": [{"name": "harbor-regcred"}]}'
      args:
        creates: /etc/kubernetes/harbor-registry-patch-done
