---
- name: Copy Kube config from master to localhost
  hosts: local
  tasks:
  
    - name: Create .kube directory for regular user
      file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: '0700'

    - name: Fetch Kube config from master
      fetch:
        src: "/root/.kube/config"
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: yes
        mode: '0600'
      delegate_to: "{{ groups['master'][0] }}"

    - name: Set file mode to 600
      file:
        path: "{{ lookup('env', 'HOME') }}/.kube/config"
        mode: '0600'

- name: Remove NoSchedule taint 
  hosts: master
  tasks:
    - name: Remove NoSchedule taint from master node
      command: kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
