apiVersion: v1
kind: Service
metadata:
  name: vpn-service
spec:
  selector:
    app: vpn
  ports:
    - name: d1
      protocol: TCP
      port: 8112
      targetPort: 8112
    - name: d2
      protocol: TCP
      port: 55555
      targetPort: 55555